// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebProjectHackathon.DataAccess.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250903195237_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("WebProjectHackathon.DataAccess.Entity.CircleContextPagesInfoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("IdContextHomePages")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdContextHomePages");

                    b.ToTable("CircleContextPagesInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Основи HTML, CSS, JavaScript. Розуміння структури веб-сторінок.",
                            IdContextHomePages = 1,
                            Title = "Вивчити основи веб-розробки"
                        },
                        new
                        {
                            Id = 2,
                            Description = "React, Vue або Angular. Компонентний підхід, SPA, state management.",
                            IdContextHomePages = 1,
                            Title = "Освоїти сучасні фреймворки та бібліотеки"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Chrome DevTools, Postman, Git, Webpack. Налагодження та оптимізація.",
                            IdContextHomePages = 1,
                            Title = "Вивчити інструменти розробника"
                        },
                        new
                        {
                            Id = 4,
                            Description = "REST API, GraphQL. Запити до серверів, обробка JSON.",
                            IdContextHomePages = 1,
                            Title = "Робота з API"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Верстка проектів, хостинг, підключення реальних API.",
                            IdContextHomePages = 1,
                            Title = "Створити портфоліо"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Фріланс, стажування, open-source проекти. Робота в команді.",
                            IdContextHomePages = 1,
                            Title = "Отримати перший комерційний досвід"
                        },
                        new
                        {
                            Id = 7,
                            Description = "JavaScript (Node.js), Python, PHP, Java або C#",
                            IdContextHomePages = 2,
                            Title = "Вивчення мови програмування"
                        },
                        new
                        {
                            Id = 8,
                            Description = "SQL (PostgreSQL, MySQL) або NoSQL (MongoDB, Firebase)",
                            IdContextHomePages = 2,
                            Title = "Робота з базами даних"
                        },
                        new
                        {
                            Id = 9,
                            Description = "MVC, REST API, GraphQL. Аутентифікація (JWT, OAuth)",
                            IdContextHomePages = 2,
                            Title = "Архітектура та серверні технології"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Docker, Kubernetes, AWS, CI/CD",
                            IdContextHomePages = 2,
                            Title = "DevOps та хмарні технології"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Створення портфоліо (GitHub). Стажування, перша робота",
                            IdContextHomePages = 2,
                            Title = "Практика та працевлаштування"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Вивчення теорії",
                            IdContextHomePages = 3,
                            Title = "Менеджмент, психологія, HR-курси"
                        },
                        new
                        {
                            Id = 13,
                            Description = "LinkedIn, Work.ua, Djinni, ATS-системи (Workable, Greenhouse)",
                            IdContextHomePages = 3,
                            Title = "Освоєння HR-інструментів"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Проведення співбесід та робота з конфліктами",
                            IdContextHomePages = 3,
                            Title = "Розвиток комунікаційних навичок"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Оформлення документів",
                            IdContextHomePages = 3,
                            Title = "Знання трудового законодавства"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Стажування у HR-відділі",
                            IdContextHomePages = 3,
                            Title = "Практика та працевлаштування"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Колір, типографіка, розташування. Контраст, баланс, ритм. Використання сіток (grid system).",
                            IdContextHomePages = 4,
                            Title = "Візуальна ієрархія"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Аналіз поведінки, тестування макетів (Google Analytics, Hotjar, A/B-тестування).",
                            IdContextHomePages = 4,
                            Title = "UX-дослідження"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Figma, Adobe XD, Sketch – створення UI, прототипування, дизайн-системи.",
                            IdContextHomePages = 4,
                            Title = "Інструменти"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Основи HTML, CSS, змінні, шрифти, кольорові схеми.",
                            IdContextHomePages = 4,
                            Title = "Код для дизайнерів"
                        },
                        new
                        {
                            Id = 21,
                            Description = "3-5 кейсів у Behance, Dribbble.",
                            IdContextHomePages = 4,
                            Title = "Портфоліо"
                        });
                });

            modelBuilder.Entity("WebProjectHackathon.DataAccess.Entity.ContextHomePagesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContextHomePages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Створює зовнішній інтерфейс сайтів та веб-додатків. Відповідає за вигляд, інтерактивність та коректну роботу веб-сторінок на різних пристроях. Використовує HTML, CSS, JavaScript та сучасні фреймворки.",
                            Title = "Frontend-розробник"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Розробляє логіку роботи сервера, баз даних та API, які забезпечують функціонування сайту. Працює з мовами програмування, такими як Python, PHP, Java, та базами даних MySQL або PostgreSQL.",
                            Title = "Backend-розробник"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Шукає та адаптує нових спеціалістів, створює комфортну атмосферу у команді, проводить співбесіди та допомагає з розвитком персоналу. Відповідає за побудову сильної корпоративної культури.",
                            Title = "HR Manager"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Проектує інтерфейси, роблячи їх зручними, доступними та привабливими для користувачів. Використовує інструменти дизайну, такі як Figma, Adobe XD, та аналізує поведінку користувачів для покращення взаємодії.",
                            Title = "UX/UI Дизайнер"
                        });
                });

            modelBuilder.Entity("WebProjectHackathon.DataAccess.Entity.MainPanelContextEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CircleContextPagesInfoEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CircleContextPagesInfoEntityId");

                    b.ToTable("MainPanelContexts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CircleContextPagesInfoEntityId = 1,
                            Context = "Основи створення веб-сторінок: структура HTML-документів, основні теги та атрибути. Використання CSS для стилізації елементів, верстка сторінок та адаптивний дизайн.",
                            Title = "HTML та CSS",
                            Url = "https://developer.mozilla.org/uk/docs/Learn9"
                        },
                        new
                        {
                            Id = 2,
                            CircleContextPagesInfoEntityId = 1,
                            Context = "Основи мови програмування JavaScript: змінні, типи даних, функції, цикли та умови. Робота з DOM (Document Object Model), події та маніпуляція HTML-елементами.",
                            Title = "JavaScript та DOM",
                            Url = "https://developer.mozilla.org/uk/docs/Web/JavaScript"
                        },
                        new
                        {
                            Id = 3,
                            CircleContextPagesInfoEntityId = 1,
                            Context = "Знайомство з серверною частиною веб-розробки. Основи роботи з базами даних (SQL, NoSQL), сервери, API та бекенд-фреймворки, наприклад, ASP.NET MVC.",
                            Title = "Основи Backend-розробки",
                            Url = "https://learn.microsoft.com/uk-ua/aspnet/mvc/"
                        },
                        new
                        {
                            Id = 4,
                            CircleContextPagesInfoEntityId = 1,
                            Context = "Використання систем контролю версій, таких як Git. Основи хостингу, деплою веб-додатків, робота з хмарними платформами (Azure, AWS).",
                            Title = "Контроль версій та розгортання",
                            Url = "https://docs.github.com/uk/get-started"
                        },
                        new
                        {
                            Id = 5,
                            CircleContextPagesInfoEntityId = 2,
                            Context = "Популярна бібліотека для створення інтерфейсів користувача. Основи роботи з компонентами, станами (state), пропсами (props) та хуками (hooks). Знайомство з JSX та віртуальним DOM.",
                            Title = "React.js",
                            Url = "https://react.dev/"
                        },
                        new
                        {
                            Id = 6,
                            CircleContextPagesInfoEntityId = 2,
                            Context = "Фреймворк від Google для побудови масштабованих SPA (Single Page Applications). Основи TypeScript, робота з компонентами, модулями, сервісами та RxJS.",
                            Title = "Angular",
                            Url = "https://source3.com"
                        },
                        new
                        {
                            Id = 7,
                            CircleContextPagesInfoEntityId = 2,
                            Context = "Простий у засвоєнні фреймворк для створення реактивних інтерфейсів. Робота з шаблонами, директивами, Vue Router та Vuex.",
                            Title = "Vue.js",
                            Url = "https://source3.com"
                        },
                        new
                        {
                            Id = 8,
                            CircleContextPagesInfoEntityId = 2,
                            Context = "Сучасний бекенд-фреймворк від Microsoft для створення веб-додатків, API та мікросервісів. Вивчення контролерів, middleware, Entity Framework Core та автентифікації.",
                            Title = "ASP.NET Core",
                            Url = "https://learn.microsoft.com/en-us/aspnet/core/"
                        },
                        new
                        {
                            Id = 9,
                            CircleContextPagesInfoEntityId = 3,
                            Context = "Набір інструментів для налагодження веб-сторінок у браузері Google Chrome. Дозволяє аналізувати HTML, CSS, JavaScript, мережеві запити, продуктивність та помилки.",
                            Title = "Chrome DevTools",
                            Url = "https://developer.mozilla.org/uk/docs/Learn9"
                        },
                        new
                        {
                            Id = 10,
                            CircleContextPagesInfoEntityId = 3,
                            Context = "Популярний інструмент для тестування API. Дозволяє надсилати HTTP-запити, перевіряти відповіді серверів, створювати колекції запитів та автоматизувати тестування.",
                            Title = "Postman",
                            Url = "https://developer.mozilla.org/uk/docs/Web/JavaScript"
                        },
                        new
                        {
                            Id = 11,
                            CircleContextPagesInfoEntityId = 3,
                            Context = "Модульний збирач JavaScript-додатків, що оптимізує код, обробляє CSS, зображення та інші ресурси. Вивчення конфігурації, лоадерів та плагінів.",
                            Title = "Webpack",
                            Url = "https://learn.microsoft.com/uk-ua/aspnet/mvc/"
                        },
                        new
                        {
                            Id = 12,
                            CircleContextPagesInfoEntityId = 3,
                            Context = "Платформа для контейнеризації, що дозволяє створювати, розгортати та керувати ізольованими середовищами для додатків. Основи Docker Compose, Docker Images та контейнерів.",
                            Title = "Docker",
                            Url = "https://docs.github.com/uk/get-started"
                        },
                        new
                        {
                            Id = 13,
                            CircleContextPagesInfoEntityId = 4,
                            Context = "Знайомство з принципами REST (Representational State Transfer), методами HTTP-запитів (GET, POST, PUT, DELETE), статус-кодами та форматами обміну даними (JSON, XML).",
                            Title = "Основи REST API",
                            Url = "https://source1.com"
                        },
                        new
                        {
                            Id = 14,
                            CircleContextPagesInfoEntityId = 4,
                            Context = "Робота з API у JavaScript: використання fetch() та бібліотеки Axios для виконання HTTP-запитів, обробка відповідей сервера та помилок.",
                            Title = "Fetch та Axios",
                            Url = "https://source2.com"
                        },
                        new
                        {
                            Id = 15,
                            CircleContextPagesInfoEntityId = 4,
                            Context = "Розробка API за допомогою ASP.NET Core: створення контролерів, обробка запитів, використання JSON Web Token (JWT) для автентифікації та взаємодія з базами даних через Entity Framework Core.",
                            Title = "API з ASP.NET Core",
                            Url = "https://source3.com"
                        },
                        new
                        {
                            Id = 16,
                            CircleContextPagesInfoEntityId = 4,
                            Context = "Після підготовки варто активно шукати можливості: Джуніор-позиції та стажування – пошук у LinkedIn, на сайтах компаній, Нетворкінг – участь у мітапах, Telegram-чатах для айтішників, Кар'єрний ріст – пробувати нові технології, покращувати софт-скіли",
                            Title = "GraphQL альтернатива REST",
                            Url = "https://source4.com"
                        },
                        new
                        {
                            Id = 17,
                            CircleContextPagesInfoEntityId = 5,
                            Context = "Портфоліо можна створити у вигляді окремого веб-сайту або розмістити на платформах типу GitHub Pages, Netlify або Vercel. Важливо продумати структуру: Головна сторінка (про себе, фото, контакти),Проекти (список з описом та посиланнями).",
                            Title = "Вибір платформи та структури",
                            Url = "https://source1.com"
                        },
                        new
                        {
                            Id = 18,
                            CircleContextPagesInfoEntityId = 5,
                            Context = "HTML, CSS, JavaScript – для створення статичного сайту, React.js, Vue.js або Angular – для динамічного портфоліо,Bootstrap або Tailwind CSS – для швидкого стилізування.",
                            Title = "Технології для розробки портфоліо",
                            Url = "https://source2.com"
                        },
                        new
                        {
                            Id = 19,
                            CircleContextPagesInfoEntityId = 5,
                            Context = "Важливо додати кілька проєктів, які демонструють навички. Для кожного проекту: Назва та короткий опис, Використані технології, Скріншоти або демо-версія.",
                            Title = "Додавання проектів",
                            Url = "https://source3.com"
                        },
                        new
                        {
                            Id = 20,
                            CircleContextPagesInfoEntityId = 5,
                            Context = "Щоб портфоліо виглядало професійно: Використовуй адаптивний дизайн, Додай анімації або інтерактивні елементи, Використовуй мета-теги та SEO-практики.",
                            Title = "Оптимізація та SEO",
                            Url = "https://source4.com"
                        },
                        new
                        {
                            Id = 21,
                            CircleContextPagesInfoEntityId = 6,
                            Context = "Один із найпростіших способів отримати перші комерційні замовлення – почати працювати на фрілансі. Реєструйся на платформах, заповнюй профіль і пропонуй свої послуги.",
                            Title = "Фріланс-платформи",
                            Url = "https://source1.com"
                        },
                        new
                        {
                            Id = 22,
                            CircleContextPagesInfoEntityId = 6,
                            Context = "Допоможи некомерційним організаціям або внеси вклад у Open Source-проєкти. Це не лише корисний досвід, але й можливість створити портфоліо та отримати рекомендації.",
                            Title = "Open Source та волонтерські проєкти",
                            Url = "https://source2.com"
                        },
                        new
                        {
                            Id = 23,
                            CircleContextPagesInfoEntityId = 6,
                            Context = "Шукай стажування або роботу на позицію Junior Developer. Деякі компанії готові брати початківців без досвіду, якщо є базові навички.",
                            Title = "Стажування та джуніор-вакансії",
                            Url = "https://source3.com"
                        },
                        new
                        {
                            Id = 24,
                            CircleContextPagesInfoEntityId = 6,
                            Context = "Знайомся з іншими розробниками та шукай можливості через знайомих. Відвідуй IT-конференції, мітапи, вебінари.",
                            Title = "Нетворкінг та знайомства",
                            Url = "https://source4.com"
                        },
                        new
                        {
                            Id = 25,
                            CircleContextPagesInfoEntityId = 7,
                            Context = "Перед початком навчання варто визначитися з мовою програмування. Вибір залежить від мети: Python, JavaScript, Java, C#, C++, Swift, Kotlin",
                            Title = "Вибір мови програмування",
                            Url = "https://devdocs.io/"
                        },
                        new
                        {
                            Id = 26,
                            CircleContextPagesInfoEntityId = 7,
                            Context = "Після вибору мови потрібно освоїти її базові конструкції: Змінні та типи даних, Оператори та умови, Цикли та функції",
                            Title = "Основи синтаксису",
                            Url = "https://source2.com"
                        },
                        new
                        {
                            Id = 27,
                            CircleContextPagesInfoEntityId = 7,
                            Context = "Бібліотеки та фреймворки допомагають пришвидшити розробку: Django, Flask – для бекенду, Spring Boot – для Java-додатків",
                            Title = "Робота з бібліотеками та фреймворками",
                            Url = "https://docs.djangoproject.com/"
                        },
                        new
                        {
                            Id = 28,
                            CircleContextPagesInfoEntityId = 7,
                            Context = "Кращий спосіб вивчити програмування – практика: Розв’язуйте задачі на алгоритми, Беріть участь у хакатонах, Розробляйте власні проєкти",
                            Title = "Практика та створення проєктів",
                            Url = "https://source2.com"
                        },
                        new
                        {
                            Id = 29,
                            CircleContextPagesInfoEntityId = 8,
                            Context = "База даних – це організований набір даних, що зберігається та керується системою управління базами даних (СУБД). Основні поняття: Реляційні БД (SQL) – MySQL, PostgreSQL. Нереляційні БД (NoSQL) – MongoDB, Redis, Cassandra та Запити SQL – SELECT, INSERT, UPDATE, DELETE",
                            Title = "Основи баз даних",
                            Url = "https://source1.com"
                        },
                        new
                        {
                            Id = 30,
                            CircleContextPagesInfoEntityId = 8,
                            Context = "Щоб створити ефективну БД, потрібно враховувати: Нормалізацію (запобігання дублюванню даних), Зв’язки між таблицями (один-до-одного, один-до-багатьох), Індекси для пришвидшення пошуку даних",
                            Title = "Проєктування баз даних",
                            Url = "https://vertabelo.com/"
                        },
                        new
                        {
                            Id = 31,
                            CircleContextPagesInfoEntityId = 8,
                            Context = "Реляційні БД використовують SQL-запити, тоді як NoSQL підходять для гнучкого зберігання даних: MySQL/PostgreSQL – класичні реляційні БД, Redis – ключ-значення для кешування, Firebase – хмарне сховище",
                            Title = "Робота з реляційними та NoSQL базами",
                            Url = "https://www.postgresql.org/docs/"
                        },
                        new
                        {
                            Id = 32,
                            CircleContextPagesInfoEntityId = 8,
                            Context = "Щоб база працювала швидко та безпечно, потрібно: Використовувати індекси для швидкого пошуку, Уникати надмірної вкладеності запитів, Захищати дані від SQL-ін’єкцій",
                            Title = "Оптимізація та безпека баз даних",
                            Url = "https://source4.com"
                        },
                        new
                        {
                            Id = 33,
                            CircleContextPagesInfoEntityId = 9,
                            Context = "Архітектура програмного забезпечення визначає структуру та взаємодію компонентів системи. Основні підходи: Монолітна архітектура – вся логіка в одному застосунку",
                            Title = "Основи архітектури програмного забезпечення",
                            Url = "https://microservices.io/"
                        },
                        new
                        {
                            Id = 34,
                            CircleContextPagesInfoEntityId = 9,
                            Context = "Серверні технології використовуються для обробки запитів та управління даними. Популярні технології: Apache, Nginx – веб-сервери для обробки HTTP-запитів, Django, Flask – Python-фреймворки для бекенду",
                            Title = "Серверні технології та веб-сервери",
                            Url = "https://source2.com"
                        },
                        new
                        {
                            Id = 35,
                            CircleContextPagesInfoEntityId = 9,
                            Context = "Сервер обробляє запити до бази даних. Основні підходи: SQL (MySQL, PostgreSQL) – для структурованих даних, NoSQL (MongoDB, Redis) – для гнучких та швидких запитів",
                            Title = "Бази даних у серверних застосунках",
                            Url = "https://source3.com"
                        },
                        new
                        {
                            Id = 36,
                            CircleContextPagesInfoEntityId = 9,
                            Context = "Щоб система була стійкою, потрібно: Балансування навантаження (Load Balancer, Nginx), Хмарні рішення (AWS, Google Cloud, Azure), Безпека (HTTPS, JWT, OAuth)",
                            Title = "Масштабування, балансування навантаження та безпека",
                            Url = "https://aws.amazon.com/"
                        },
                        new
                        {
                            Id = 37,
                            CircleContextPagesInfoEntityId = 10,
                            Context = "DevOps – це методологія, що поєднує розробку (Development) та операційну діяльність (Operations).",
                            Title = "Основи DevOps",
                            Url = "https://source1.com"
                        },
                        new
                        {
                            Id = 38,
                            CircleContextPagesInfoEntityId = 10,
                            Context = "Автоматизація – ключовий аспект DevOps. Основні інструменти: Контейнери – Docker, Podman, Jenkins, GitLab CI.",
                            Title = "Інструменти DevOps",
                            Url = "https://kubernetes.io/"
                        },
                        new
                        {
                            Id = 39,
                            CircleContextPagesInfoEntityId = 10,
                            Context = "Хмарні платформи надають інструменти для масштабування та керування інфраструктурою: AWS (Amazon Web Services)",
                            Title = "Хмарні технології",
                            Url = "https://learn.microsoft.com/en-us/azure/"
                        },
                        new
                        {
                            Id = 40,
                            CircleContextPagesInfoEntityId = 10,
                            Context = "Для стабільної роботи системи важливо впровадити моніторинг та безпеку: Моніторинг логів та продуктивності",
                            Title = "Моніторинг та безпека",
                            Url = "https://source4.com"
                        },
                        new
                        {
                            Id = 41,
                            CircleContextPagesInfoEntityId = 11,
                            Context = "Для успішного працевлаштування важливо мати реальний досвід роботи з технологіями. Особисті проєкти, Open Source, Фріланс, Хакатони та конкурси.",
                            Title = "Практичний досвід та створення проєктів",
                            Url = "https://www.codewars.com/"
                        },
                        new
                        {
                            Id = 42,
                            CircleContextPagesInfoEntityId = 11,
                            Context = "Щоб зацікавити роботодавця, потрібно грамотно оформити резюме та портфоліо: Резюме, Портфоліо, LinkedIn.",
                            Title = "Написання резюме та портфоліо",
                            Url = "https://source2.com"
                        },
                        new
                        {
                            Id = 43,
                            CircleContextPagesInfoEntityId = 11,
                            Context = "Для успішного проходження співбесід потрібно: Алгоритмічні завдання, Питання щодо структур даних та алгоритмів, Підготовка до технічної співбесіди.",
                            Title = "Підготовка до співбесіди",
                            Url = "https://www.hackerrank.com/"
                        },
                        new
                        {
                            Id = 44,
                            CircleContextPagesInfoEntityId = 11,
                            Context = "Джуніор-позиції та стажування – пошук у LinkedIn, на сайтах компаній, Нетворкінг, Кар'єрний ріст – пробувати нові технології, покращувати софт-скіли",
                            Title = "Пошук роботи та перші кроки в кар'єрі",
                            Url = "https://source4.com"
                        },
                        new
                        {
                            Id = 45,
                            CircleContextPagesInfoEntityId = 12,
                            Context = "Основи управління персоналом, психологія роботи з людьми та підбір кадрів: Основи менеджменту: як знайти, мотивувати та утримати співробітників.",
                            Title = "HR-менеджер",
                            Url = "https://source1.com"
                        },
                        new
                        {
                            Id = 46,
                            CircleContextPagesInfoEntityId = 12,
                            Context = "Знайомство з платформами для пошуку кандидатів та автоматизація рекрутингу: LinkedIn, Work.ua, Djinni: пошук та аналіз профілів, ATS-системи (Workable, Greenhouse, BambooHR): автоматизація процесу найму.",
                            Title = "Освоєння HR-інструментів",
                            Url = "https://source2.com"
                        },
                        new
                        {
                            Id = 47,
                            CircleContextPagesInfoEntityId = 12,
                            Context = "Навички проведення співбесід та вирішення конфліктів у командах: Підготовка ефективних питань та оцінка відповідей кандидатів, визначення мотивації та рівня професіоналізму претендента.",
                            Title = "Розвиток комунікаційних навичок",
                            Url = "https://source3.com"
                        },
                        new
                        {
                            Id = 48,
                            CircleContextPagesInfoEntityId = 12,
                            Context = "Оформлення документації та правові аспекти працевлаштування: Контракти, політики компанії, NDA, законодавчі вимоги щодо працевлаштування та оформлення співробітників.",
                            Title = "Знання трудового законодавства",
                            Url = "https://source4.com"
                        },
                        new
                        {
                            Id = 49,
                            CircleContextPagesInfoEntityId = 13,
                            Context = "Вивчення методів збору та аналізу даних про співробітників для оцінки їхньої ефективності та побудови метрик продуктивності.",
                            Title = "Основи HR-аналізу",
                            Url = "https://source1.com"
                        },
                        new
                        {
                            Id = 50,
                            CircleContextPagesInfoEntityId = 13,
                            Context = "Використання інструментів для автоматизації процесів підбору кандидатів, таких як HR-боти та онлайн-платформи для співбесід та тестування.",
                            Title = "Підбір та найм персоналу",
                            Url = "https://source2.com"
                        },
                        new
                        {
                            Id = 51,
                            CircleContextPagesInfoEntityId = 13,
                            Context = "Застосування інструментів для вимірювання рівня залученості та визначення факторів, що впливають на мотивацію та утримання співробітників.",
                            Title = "Аналіз залученості співробітників",
                            Url = "https://source3.com"
                        },
                        new
                        {
                            Id = 52,
                            CircleContextPagesInfoEntityId = 13,
                            Context = "Освоєння програмних рішень для автоматизації HR-процесів, включаючи розрахунок заробітної плати, управління відпустками та лікарняними.",
                            Title = "HR-автоматизація та ІТ-інструменти",
                            Url = "https://source4.com"
                        },
                        new
                        {
                            Id = 53,
                            CircleContextPagesInfoEntityId = 14,
                            Context = "Вивчення принципів та технік ефективного спілкування, зокрема активного слухання та чіткої передачі інформації.",
                            Title = "Основи ефективної комунікації",
                            Url = "https://source1.com"
                        },
                        new
                        {
                            Id = 54,
                            CircleContextPagesInfoEntityId = 14,
                            Context = "Розвиток навичок розв'язання конфліктних ситуацій у команді, використання технік для конструктивного вирішення суперечок.",
                            Title = "Управління конфліктами",
                            Url = "https://source2.com"
                        },
                        new
                        {
                            Id = 55,
                            CircleContextPagesInfoEntityId = 14,
                            Context = "Опанування стратегій для ефективної роботи в команді, в тому числі обговорення ідей, обміну інформацією та підтримки колег.",
                            Title = "Командна комунікація",
                            Url = "https://source3.com"
                        },
                        new
                        {
                            Id = 56,
                            CircleContextPagesInfoEntityId = 14,
                            Context = "Розвиток навичок взаємодії з різними людьми, включаючи встановлення контактів, створення довірливих відносин і адаптацію до різних стилів спілкування.",
                            Title = "Міжособистісні комунікації",
                            Url = "https://source4.com"
                        },
                        new
                        {
                            Id = 57,
                            CircleContextPagesInfoEntityId = 15,
                            Context = "Вивчення основних положень трудового кодексу та законів, що регулюють права та обов'язки роботодавців і працівників.",
                            Title = "Основи трудового законодавства",
                            Url = "https://source1.com"
                        },
                        new
                        {
                            Id = 58,
                            CircleContextPagesInfoEntityId = 15,
                            Context = "Опанування процесами укладання трудових договорів, реєстрації працівників, а також розуміння різних видів трудових контрактів.",
                            Title = "Оформлення трудових відносин",
                            Url = "https://source2.com"
                        },
                        new
                        {
                            Id = 59,
                            CircleContextPagesInfoEntityId = 15,
                            Context = "Знання прав та обов'язків сторін трудових відносин, включаючи питання оплати праці, відпусток, лікарняних та дисциплінарних санкцій.",
                            Title = "Права та обов'язки працівників і роботодавців",
                            Url = "https://source3.com"
                        },
                        new
                        {
                            Id = 60,
                            CircleContextPagesInfoEntityId = 15,
                            Context = "Ознайомлення з процедурами вирішення трудових спорів, звернення до органів праці та судових установ, а також медіація в трудових питаннях.",
                            Title = "Урегулювання трудових суперечок",
                            Url = "https://source4.com"
                        },
                        new
                        {
                            Id = 61,
                            CircleContextPagesInfoEntityId = 16,
                            Context = "Опанування методів ефективного пошуку роботи, створення резюме та супровідного листа, а також підготовка до співбесід.",
                            Title = "Пошук та підбір роботи",
                            Url = "https://source1.com"
                        },
                        new
                        {
                            Id = 62,
                            CircleContextPagesInfoEntityId = 16,
                            Context = "Вивчення кроків для успішної адаптації на новій посаді, знайомство з корпоративною культурою та вимогами компанії.",
                            Title = "Процес адаптації на новому місці роботи",
                            Url = "https://source2.com"
                        },
                        new
                        {
                            Id = 63,
                            CircleContextPagesInfoEntityId = 16,
                            Context = "Планування та розвиток кар'єри, участь у навчальних програмах, підвищення кваліфікації та просування по службі.",
                            Title = "Професійний розвиток та кар'єрне зростання",
                            Url = "https://source3.com"
                        },
                        new
                        {
                            Id = 64,
                            CircleContextPagesInfoEntityId = 16,
                            Context = "Знання правових норм щодо працевлаштування, укладення контрактів, трудових відносин, а також захисту прав працівників.",
                            Title = "Законодавчі аспекти працевлаштування",
                            Url = "https://source4.com"
                        },
                        new
                        {
                            Id = 65,
                            CircleContextPagesInfoEntityId = 17,
                            Context = "Організація елементів інтерфейсу за рівнем важливості, використовуючи розмір, колір, контраст і простір.",
                            Title = "Візуальна ієрархія",
                            Url = "https://source1.com"
                        },
                        new
                        {
                            Id = 66,
                            CircleContextPagesInfoEntityId = 17,
                            Context = "Вибір шрифтів, їх поєднання, розмір та інтервали для зручності читання і візуальної гармонії.",
                            Title = "Типографіка в UI/UX",
                            Url = "https://source2.com"
                        },
                        new
                        {
                            Id = 67,
                            CircleContextPagesInfoEntityId = 17,
                            Context = "Використання кольорової палітри для передачі настрою, підвищення зручності використання та створення акцентів.",
                            Title = "Колір та контраст",
                            Url = "https://source3.com"
                        },
                        new
                        {
                            Id = 68,
                            CircleContextPagesInfoEntityId = 17,
                            Context = "Використання сіткових систем для впорядкування контенту та забезпечення гармонійного розташування елементів.",
                            Title = "Сітки та вирівнювання",
                            Url = "https://source4.com"
                        },
                        new
                        {
                            Id = 69,
                            CircleContextPagesInfoEntityId = 18,
                            Context = "Визначення потреб, поведінки та очікувань користувачів за допомогою опитувань, інтерв’ю та аналізу даних.",
                            Title = "Аналіз цільової аудиторії",
                            Url = "https://source1.com"
                        },
                        new
                        {
                            Id = 70,
                            CircleContextPagesInfoEntityId = 18,
                            Context = "Перевірка зручності використання продукту через спостереження за реальними користувачами та виявлення проблем у взаємодії.",
                            Title = "Юзабіліті-тестування",
                            Url = "https://source2.com"
                        },
                        new
                        {
                            Id = 71,
                            CircleContextPagesInfoEntityId = 18,
                            Context = "Розробка узагальнених портретів користувачів для кращого розуміння їхніх цілей, мотивації та болей.",
                            Title = "Створення персон користувачів",
                            Url = "https://source3.com"
                        },
                        new
                        {
                            Id = 72,
                            CircleContextPagesInfoEntityId = 18,
                            Context = "Візуалізація взаємодії користувача з продуктом, виявлення проблемних точок і можливостей для покращення UX.",
                            Title = "Картування користувацького шляху (User Journey)",
                            Url = "https://source4.com"
                        },
                        new
                        {
                            Id = 73,
                            CircleContextPagesInfoEntityId = 19,
                            Context = "Популярний інструмент для створення макетів, прототипування та спільної роботи над дизайном.",
                            Title = "Figma",
                            Url = "https://source1.com"
                        },
                        new
                        {
                            Id = 74,
                            CircleContextPagesInfoEntityId = 19,
                            Context = "Програма для проєктування інтерфейсів, створення інтерактивних прототипів і тестування UX-рішень.",
                            Title = "Adobe XD",
                            Url = "https://source2.com"
                        },
                        new
                        {
                            Id = 75,
                            CircleContextPagesInfoEntityId = 19,
                            Context = "Інструмент для розробки UI-дизайну, що використовується переважно на macOS, із широкими можливостями плагінів.",
                            Title = "Sketch",
                            Url = "https://source3.com"
                        },
                        new
                        {
                            Id = 76,
                            CircleContextPagesInfoEntityId = 19,
                            Context = "Онлайн-дошка для командної роботи, мозкового штурму, створення схем користувацького шляху та UX-досліджень.",
                            Title = "Miro",
                            Url = "https://source4.com"
                        },
                        new
                        {
                            Id = 77,
                            CircleContextPagesInfoEntityId = 20,
                            Context = "Вивчення базової структури веб-сторінок, стилізація елементів та створення адаптивного дизайну.",
                            Title = "Основи HTML та CSS",
                            Url = "https://source1.com"
                        },
                        new
                        {
                            Id = 78,
                            CircleContextPagesInfoEntityId = 20,
                            Context = "Додавання динаміки до інтерфейсу за допомогою анімацій, плавних переходів і ефектів наведення.",
                            Title = "CSS-анімації та переходи",
                            Url = "https://source2.com"
                        },
                        new
                        {
                            Id = 79,
                            CircleContextPagesInfoEntityId = 20,
                            Context = "Використання JavaScript для інтерактивності, таких як модальні вікна, випадаючі меню та динамічний контент.",
                            Title = "Основи JavaScript для UI",
                            Url = "https://source3.com"
                        },
                        new
                        {
                            Id = 80,
                            CircleContextPagesInfoEntityId = 20,
                            Context = "Використання готових компонентів і стилів для прискорення розробки та уніфікації дизайну.",
                            Title = "Фреймворки та бібліотеки (Bootstrap, Tailwind CSS)",
                            Url = "https://source4.com"
                        },
                        new
                        {
                            Id = 81,
                            CircleContextPagesInfoEntityId = 21,
                            Context = "Включення кількох ваших найкращих проєктів, які демонструють ваші навички в дизайні, дослідженнях та прототипуванні.",
                            Title = "Демонстрація проєктів",
                            Url = "https://source1.com"
                        },
                        new
                        {
                            Id = 82,
                            CircleContextPagesInfoEntityId = 21,
                            Context = "Документування етапів роботи над проєктами, від досліджень до реалізації, щоб показати ваше розуміння процесу UX/UI-дизайну.",
                            Title = "Опис процесу роботи",
                            Url = "https://source2.com"
                        },
                        new
                        {
                            Id = 83,
                            CircleContextPagesInfoEntityId = 21,
                            Context = "Додавання інтерактивних прототипів, щоб потенційні клієнти могли взаємодіяти з вашим дизайном і бачити його в дії.",
                            Title = "Інтерактивні прототипи",
                            Url = "https://source3.com"
                        },
                        new
                        {
                            Id = 84,
                            CircleContextPagesInfoEntityId = 21,
                            Context = "Додавання відгуків клієнтів або колег, які можуть підтвердити вашу професійну кваліфікацію та досвід.",
                            Title = "Відгуки та рекомендації",
                            Url = "https://source4.com"
                        });
                });

            modelBuilder.Entity("WebProjectHackathon.DataAccess.Entity.CircleContextPagesInfoEntity", b =>
                {
                    b.HasOne("WebProjectHackathon.DataAccess.Entity.ContextHomePagesEntity", "ContextHomePage")
                        .WithMany("CircleContextPagesInfo")
                        .HasForeignKey("IdContextHomePages")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContextHomePage");
                });

            modelBuilder.Entity("WebProjectHackathon.DataAccess.Entity.MainPanelContextEntity", b =>
                {
                    b.HasOne("WebProjectHackathon.DataAccess.Entity.CircleContextPagesInfoEntity", "CircleContextPageInfo")
                        .WithMany("mainPanelContext")
                        .HasForeignKey("CircleContextPagesInfoEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CircleContextPageInfo");
                });

            modelBuilder.Entity("WebProjectHackathon.DataAccess.Entity.CircleContextPagesInfoEntity", b =>
                {
                    b.Navigation("mainPanelContext");
                });

            modelBuilder.Entity("WebProjectHackathon.DataAccess.Entity.ContextHomePagesEntity", b =>
                {
                    b.Navigation("CircleContextPagesInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
